spring:
  #数据源配置
  data:
    mongodb:
      # 主机地址
      host: 8.131.95.101
      # 数据库
      database: test
      # 端口
      port: 27017
      #也可以使用uri连接
      #uri: mongodb://8.131.95.10:27017/test